networks:
  internal:
    driver: bridge

volumes:
  sql_data:

services:
  gateway:
    build:
      context: ./src
      dockerfile: ClientGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      CUSTOMERS_BASEURL: "http://customers:8080"
      ACCOUNTS_BASEURL: "http://accounts:8080"
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - customers
      - accounts
    networks:
      - internal

  customers:
    build:
      context: ./src
      dockerfile: Customers/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionString: "Server=${DB_HOST},${DB_PORT};Database=${CUSTOMERS_DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;"
    networks:
      - internal

  accounts:
    build:
      context: ./src
      dockerfile: Accounts/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionString: "Server=${DB_HOST},${DB_PORT};Database=${ACCOUNTS_DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;"
    networks:
      - internal

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
