networks:
  internal:
    driver: bridge
  database:
    driver: bridge

volumes:
  sql_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - database

  customers:
    build:
      context: ./src
      dockerfile: Customers/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CUSTOMERS_DB_NAME: ${CUSTOMERS_DB_NAME}
    networks:
      - internal
      - database
    depends_on:
      - sqlserver

  accounts:
    build:
      context: ./src
      dockerfile: Accounts/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCOUNTS_DB_NAME: ${ACCOUNTS_DB_NAME}
    networks:
      - internal
      - database
    depends_on:
      - sqlserver

  gateway:
    build:
      context: ./src
      dockerfile: ClientGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
      CUSTOMERS_BASEURL: "http://customers:8080"
      ACCOUNTS_BASEURL: "http://accounts:8080"
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - customers
      - accounts
      - sqlserver
    networks:
      - internal
